
import React from 'react';
import { Metadata } from 'next';
import HeroComponent from "@/components/HeroComponent";
import FooterComponent from "@/components/FooterComponent";
import BannerComponent from "@/components/BannerComponent";
import SkillComponent from "@/components/SkillComponent";
import Project from "@/components/Project";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const Page = () => {
    return <>
        {/*<BannerComponent />*/}
        <Nav />
        <HeroComponent />
        <SkillComponent />
        <Project />
        <FooterComponent />

    </>
}
export default Page;