import React from 'react';
import { Metadata } from 'next';
import HeroComponent from "@/components/HeroComponent";
import FooterComponent from "@/components/FooterComponent";
import BannerComponent from "@/components/BannerComponent";
import SkillComponent from "@/components/SkillComponent";
import Project from "@/components/Project";
import Nav from "@/components/Nav";
import About from "@/components/About";
import Testimonials from "@/components/Testimonials";
import NewslatterSection from "@/components/NewslatterSection";


const navigation = [
    { name: 'Home', href:"#hero" },
    { name: 'Skill', href: '#skills' },
    { name: 'Project', href: '#projects' },
    { name: 'Testimonials', href: '#testimonials' },
    { name: 'About', href: '#about' },
    { name: 'Contact', href: '#newsletter'},
];



export const metadata: Metadata = {
    title: 'Abhishek Kumar',
    description: 'Generated by create next app',
}

const Page = () => {
    return <>
        {/*<BannerComponent />*/}
            <Nav navigation={navigation} />

        <section id="hero">
            <HeroComponent />
        </section>

        <section id="skills">
            <SkillComponent />
        </section>

        <section id="projects">
            <Project />
        </section>

        <section id="testimonials">
            <Testimonials />
        </section>

        <section id="about">
            <About />
        </section>

        <section id="newsletter">
            <NewslatterSection />
        </section>

        <FooterComponent />

    </>
}
export default Page;


//
//
// import React from 'react';
// import { Metadata } from 'next';
// import HeroComponent from "@/components/HeroComponent";
// import FooterComponent from "@/components/FooterComponent";
// import BannerComponent from "@/components/BannerComponent";
// import SkillComponent from "@/components/SkillComponent";
// import Project from "@/components/Project";
// import Nav from "@/components/Nav";
// import About from "@/components/About";
// import Testimonials from "@/components/Testimonials";
// import NewslatterSection from "@/components/NewslatterSection";
// //
//
//
// const Page = () => {
//     return (
//         <>
//             <nav className="bg-blue-500 p-4">
//                 <div className="container mx-auto flex justify-between items-center">
//                     <a href="#hero" className="text-white text-lg font-semibold">Home</a>
//                     <a href="#skills" className="text-white">Skills</a>
//                     <a href="#projects" className="text-white">Projects</a>
//                     <a href="#testimonials" className="text-white">Testimonials</a>
//                     <a href="#about" className="text-white">About</a>
//                     <a href="#newsletter" className="text-white">Newsletter</a>
//                 </div>
//             </nav>
//
//             <section id="hero">
//                 <HeroComponent />
//             </section>
//
//             <section id="skills">
//                 <SkillComponent />
//             </section>
//
//             <section id="projects">
//                 <Project />
//             </section>
//
//             <section id="testimonials">
//                 <Testimonials />
//             </section>
//
//             <section id="about">
//                 <About />
//             </section>
//
//             <section id="newsletter">
//                 <NewslatterSection />
//             </section>
//
//             <FooterComponent />
//         </>
//     );
// };
//
// export default Page;
